CREATE TABLE admin_accounts (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,
 email VARCHAR(255) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL,
 full_name VARCHAR(255),
 active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
);
INSERT INTO admin_accounts (email,password_hash,full_name) VALUES ('admin@gastroai.vn','$2a$10$J/DOi7aiZ88yGWYUH.wi7OdHig/.KoUaLZl8I3AhN24Svzr8MX8te','Quan tri vien GastroAI');
